/* ═══════════════════════════════════════
   VISION 2030 QUIZ — QUESTION BANK
   ~120 questions across 6 categories,
   4 difficulty levels each.
═══════════════════════════════════════ */

export type CategoryId = "neom" | "vision" | "culture" | "geography" | "history" | "arabic";

export interface Category {
  id: CategoryId;
  name: string;
  nameAr: string;
  emoji: string;
  description: string;
  color: string;
}

export interface Question {
  id: number;
  category: CategoryId;
  difficulty: 1 | 2 | 3 | 4;
  question: string;
  options: string[];
  correct: number;
  explanation: string;
  hint: string;
  funFact?: string;
}

export const CATEGORIES: Category[] = [
  { id: "neom",      name: "NEOM & Megaprojects",       nameAr: "نيوم والمشاريع العملاقة",  emoji: "\uD83C\uDFD7\uFE0F", description: "THE LINE, Oxagon, Trojena, and Saudi's futuristic cities",    color: "#06b6d4" },
  { id: "vision",    name: "Vision 2030 Goals",          nameAr: "أهداف رؤية ٢٠٣٠",         emoji: "\uD83D\uDCCA", description: "Pillars, economic reform, entertainment, tourism, and PIF",   color: "#8b5cf6" },
  { id: "culture",   name: "Saudi Culture & Heritage",   nameAr: "الثقافة والتراث السعودي",  emoji: "\uD83C\uDFAD", description: "Traditions, cuisine, festivals, art, and Saudi hospitality",   color: "#f59e0b" },
  { id: "geography", name: "Geography & Landmarks",      nameAr: "الجغرافيا والمعالم",       emoji: "\uD83C\uDF0D", description: "Regions, deserts, mountains, seas, and natural wonders",       color: "#22c55e" },
  { id: "history",   name: "History & Kings",             nameAr: "التاريخ والملوك",          emoji: "\uD83D\uDCDC", description: "Founding of Saudi Arabia, unification, and key milestones",    color: "#ef4444" },
  { id: "arabic",    name: "Arabic Language",             nameAr: "اللغة العربية",            emoji: "\uD83D\uDDE3\uFE0F", description: "Common phrases, greetings, numbers, and Saudi dialect",       color: "#ec4899" },
];

export const QUESTIONS: Question[] = [
  // ═══════════════════════════════════
  //  NEOM & MEGAPROJECTS (20 questions)
  // ═══════════════════════════════════

  // Difficulty 1 — Easy
  { id: 1, category: "neom", difficulty: 1, question: "What is NEOM?", options: ["A megacity project in northwest Saudi Arabia", "A Saudi airline company", "A university in Riyadh", "An oil refinery"], correct: 0, explanation: "NEOM is a $500 billion megacity being built in Tabuk Province, northwest Saudi Arabia, as part of Vision 2030.", hint: "Think big — a massive development project being built in the desert, not a company or school." },
  { id: 2, category: "neom", difficulty: 1, question: "THE LINE is a city designed to be how long?", options: ["170 km", "50 km", "500 km", "10 km"], correct: 0, explanation: "THE LINE is designed to be a 170 km linear city with zero cars and zero carbon emissions.", hint: "It's longer than most cities but measured in hundreds, not thousands, of kilometers." },
  { id: 3, category: "neom", difficulty: 1, question: "Which Saudi Crown Prince announced the NEOM project?", options: ["Mohammed bin Salman", "Sultan bin Abdulaziz", "Nayef bin Abdulaziz", "Khalid bin Faisal"], correct: 0, explanation: "Crown Prince Mohammed bin Salman (MBS) announced NEOM in October 2017 at the Future Investment Initiative.", hint: "He is commonly known by his initials — MBS." },
  { id: 4, category: "neom", difficulty: 1, question: "What does NEOM aim to have zero of?", options: ["Cars and carbon emissions", "Hotels and restaurants", "Schools and hospitals", "Parks and gardens"], correct: 0, explanation: "NEOM, particularly THE LINE, is designed for zero cars and zero carbon emissions, powered by 100% renewable energy.", hint: "Think about environmental goals — what would a green city eliminate?" },
  { id: 5, category: "neom", difficulty: 1, question: "Qiddiya is being built as Saudi Arabia's what?", options: ["Entertainment capital", "Financial center", "Agricultural hub", "Technology park"], correct: 0, explanation: "Qiddiya is a giga-project southwest of Riyadh designed to be Saudi Arabia's capital of entertainment, sports, and the arts.", hint: "It's about fun, sports, and the arts — not business or farming." },

  // Difficulty 2 — Medium
  { id: 6, category: "neom", difficulty: 2, question: "What is Oxagon in the NEOM project?", options: ["A floating industrial city", "A ski resort", "An underwater hotel", "A space launch site"], correct: 0, explanation: "Oxagon is NEOM's reimagined industrial city, featuring the world's largest floating structure and advanced manufacturing.", hint: "It floats on water and focuses on industry and manufacturing." },
  { id: 7, category: "neom", difficulty: 2, question: "Trojena in NEOM will feature which unexpected attraction?", options: ["An outdoor ski resort", "A volcano theme park", "A deep-sea aquarium", "A zero-gravity zone"], correct: 0, explanation: "Trojena will offer year-round outdoor skiing in the mountains of NEOM and will host the 2029 Asian Winter Games.", hint: "Snow in the desert? This mountain destination hosts winter sports." },
  { id: 8, category: "neom", difficulty: 2, question: "How wide is THE LINE designed to be?", options: ["200 meters", "2 km", "50 meters", "1 km"], correct: 0, explanation: "THE LINE is only 200 meters wide but 170 km long and 500 meters tall — a completely new concept in urban design.", hint: "It's surprisingly narrow for a city — think in hundreds of meters, not kilometers." },
  { id: 9, category: "neom", difficulty: 2, question: "The Red Sea Global project is focused on what?", options: ["Luxury tourism and eco-resorts", "Oil exploration", "Military installations", "Data centers"], correct: 0, explanation: "The Red Sea Global is a luxury regenerative tourism destination across 50+ islands on Saudi Arabia's west coast.", hint: "Islands, beaches, and nature — a premium travel destination." },
  { id: 10, category: "neom", difficulty: 2, question: "How tall will THE LINE be at its peak?", options: ["500 meters", "200 meters", "1,000 meters", "100 meters"], correct: 0, explanation: "THE LINE will reach 500 meters in height, with mirrored facades reflecting the surrounding desert landscape.", hint: "About as tall as a supertall skyscraper — half a kilometer." },

  // Difficulty 3 — Hard
  { id: 11, category: "neom", difficulty: 3, question: "In which province of Saudi Arabia is NEOM located?", options: ["Tabuk", "Riyadh", "Mecca", "Eastern Province"], correct: 0, explanation: "NEOM is located in Tabuk Province in the far northwest of Saudi Arabia, bordering Egypt and Jordan.", hint: "Look to the far northwest corner of Saudi Arabia, near Egypt and Jordan." },
  { id: 12, category: "neom", difficulty: 3, question: "Which international event will Trojena host in 2029?", options: ["Asian Winter Games", "FIFA World Cup", "Olympic Games", "World Expo"], correct: 0, explanation: "Trojena was selected to host the 2029 Asian Winter Games, a first for the region.", hint: "It's a continental sporting event related to cold-weather sports." },
  { id: 13, category: "neom", difficulty: 3, question: "NEOM Bay will serve as what within the megacity?", options: ["The main residential and commercial marina hub", "An airport", "A desalination plant", "A solar farm"], correct: 0, explanation: "NEOM Bay is the marina and coastal community that will be the vibrant heart of the NEOM megacity.", hint: "Think waterfront living — a marina community by the sea." },
  { id: 14, category: "neom", difficulty: 3, question: "How many islands does The Red Sea Global project span?", options: ["Over 50", "10", "5", "100"], correct: 0, explanation: "The Red Sea Global project encompasses over 50 pristine islands, with the first resorts opening in phases.", hint: "More than a few dozen islands but not a hundred." },
  { id: 15, category: "neom", difficulty: 3, question: "What is Sindalah in the NEOM project?", options: ["A luxury island resort", "A tech innovation hub", "A renewable energy farm", "A transportation terminal"], correct: 0, explanation: "Sindalah is NEOM's luxury island destination in the Red Sea, featuring yacht clubs, hotels, and fine dining.", hint: "An island paradise for the wealthy — think yachts and fine dining." },

  // Difficulty 4 — Expert
  { id: 16, category: "neom", difficulty: 4, question: "What year was the NEOM project officially announced?", options: ["2017", "2016", "2018", "2020"], correct: 0, explanation: "NEOM was announced on October 24, 2017 at the Future Investment Initiative (FII) conference in Riyadh.", hint: "It was announced at the FII conference, one year after Vision 2030 launched." },
  { id: 17, category: "neom", difficulty: 4, question: "What is the estimated total investment for the NEOM project?", options: ["$500 billion", "$100 billion", "$1 trillion", "$250 billion"], correct: 0, explanation: "NEOM has a planned investment of over $500 billion, funded mainly by the Public Investment Fund (PIF).", hint: "A staggering amount — half a trillion dollars." },
  { id: 18, category: "neom", difficulty: 4, question: "NEOM's name combines 'neo' (new) with which Arabic letter?", options: ["Meem (M) — for Mustaqbal (future)", "Alif (A)", "Noon (N)", "Baa (B)"], correct: 0, explanation: "NEOM combines the Greek prefix 'neo' (new) with the Arabic letter 'meem', the first letter of 'Mustaqbal' (future).", hint: "The last letter in NEOM comes from the Arabic word for 'future'." },
  { id: 19, category: "neom", difficulty: 4, question: "Jeddah Tower (Kingdom Tower), once completed, aims to exceed what height?", options: ["1,000 meters", "800 meters", "500 meters", "1,500 meters"], correct: 0, explanation: "Jeddah Tower aims to become the first building to exceed 1,000 meters (1 km) in height.", hint: "It aims to be the first building to reach a full kilometer tall." },
  { id: 20, category: "neom", difficulty: 4, question: "What percentage of energy in THE LINE will come from renewable sources?", options: ["100%", "80%", "50%", "70%"], correct: 0, explanation: "THE LINE is designed to run on 100% renewable energy, with zero-carbon emissions as a core principle.", hint: "THE LINE's environmental ambition is absolute — nothing less than total." },

  // ═══════════════════════════════════
  //  VISION 2030 GOALS (20 questions)
  // ═══════════════════════════════════

  // Difficulty 1
  { id: 21, category: "vision", difficulty: 1, question: "In which year was Saudi Vision 2030 launched?", options: ["2016", "2020", "2030", "2010"], correct: 0, explanation: "Vision 2030 was launched on April 25, 2016 by Crown Prince Mohammed bin Salman.", hint: "It was launched in the mid-2010s, well before the year in its name." },
  { id: 22, category: "vision", difficulty: 1, question: "What is the main goal of Vision 2030?", options: ["Diversify the economy beyond oil", "Increase oil production", "Build more mosques", "Expand military power"], correct: 0, explanation: "Vision 2030 aims to reduce Saudi Arabia's dependence on oil by diversifying the economy into tourism, tech, and entertainment.", hint: "Saudi Arabia wants to rely less on its most famous natural resource." },
  { id: 23, category: "vision", difficulty: 1, question: "What does PIF stand for?", options: ["Public Investment Fund", "Private Insurance Fund", "Petroleum Industry Foundation", "Personal Income Facility"], correct: 0, explanation: "The Public Investment Fund (PIF) is Saudi Arabia's sovereign wealth fund, a key engine of Vision 2030.", hint: "It's a sovereign wealth fund — the first word is 'Public'." },
  { id: 24, category: "vision", difficulty: 1, question: "Vision 2030 aims to increase Saudi tourism to attract how many visitors annually?", options: ["100 million", "10 million", "50 million", "1 billion"], correct: 0, explanation: "Vision 2030 targets 100 million annual visits to Saudi Arabia through tourism development and cultural events.", hint: "A very ambitious number — think nine figures." },
  { id: 25, category: "vision", difficulty: 1, question: "What is Saudization (Nitaqat)?", options: ["A program to increase Saudi nationals in the workforce", "A new city project", "A cultural festival", "A trade agreement"], correct: 0, explanation: "Saudization (Nitaqat) is a policy to increase employment of Saudi nationals in the private sector.", hint: "The name suggests making the workforce more Saudi." },

  // Difficulty 2
  { id: 26, category: "vision", difficulty: 2, question: "How many pillars does Vision 2030 have?", options: ["3", "5", "7", "2"], correct: 0, explanation: "Vision 2030 has 3 pillars: A Vibrant Society, A Thriving Economy, and An Ambitious Nation.", hint: "A small number — one for society, one for economy, one for the nation." },
  { id: 27, category: "vision", difficulty: 2, question: "Which authority was created to develop entertainment in Saudi Arabia?", options: ["General Entertainment Authority (GEA)", "Saudi Sports Authority", "National Tourism Board", "Ministry of Fun"], correct: 0, explanation: "The General Entertainment Authority (GEA) was established in 2016 to build a vibrant entertainment sector.", hint: "Its name includes the words 'General' and 'Entertainment'." },
  { id: 28, category: "vision", difficulty: 2, question: "What major change did Saudi Arabia make regarding women driving?", options: ["Lifted the ban in 2018", "Banned it in 2018", "No change was made", "Allowed it only in cities"], correct: 0, explanation: "Saudi Arabia lifted the ban on women driving on June 24, 2018, a landmark reform under Vision 2030.", hint: "A historic reform that gave women more freedom of mobility." },
  { id: 29, category: "vision", difficulty: 2, question: "The Saudi entertainment sector was revived with the return of what in 2018?", options: ["Public cinema screenings", "Horse racing", "Radio broadcasting", "Live TV shows"], correct: 0, explanation: "After a 35-year ban, commercial cinemas reopened in Saudi Arabia in April 2018 under Vision 2030 reforms.", hint: "People could finally watch movies on the big screen again after decades." },
  { id: 30, category: "vision", difficulty: 2, question: "What is Saudi Arabia's goal for non-oil revenue by 2030?", options: ["1 trillion SAR", "100 billion SAR", "500 billion SAR", "2 trillion SAR"], correct: 0, explanation: "Vision 2030 targets increasing non-oil government revenue to 1 trillion SAR annually by 2030.", hint: "The target is a round number in the trillions of Saudi Riyals." },

  // Difficulty 3
  { id: 31, category: "vision", difficulty: 3, question: "What percentage of GDP does Vision 2030 aim to have from the private sector?", options: ["65%", "40%", "50%", "80%"], correct: 0, explanation: "Vision 2030 targets raising the private sector's contribution to GDP from 40% to 65%.", hint: "The goal is roughly two-thirds of GDP." },
  { id: 32, category: "vision", difficulty: 3, question: "SharekTech is associated with which Vision 2030 goal?", options: ["Digital transformation and e-government", "Oil exploration", "Military expansion", "Agricultural reform"], correct: 0, explanation: "Digital transformation is a key Vision 2030 goal, with initiatives to make government services digital-first.", hint: "The word 'Tech' in the name gives it away — it's about going digital." },
  { id: 33, category: "vision", difficulty: 3, question: "Vision 2030 targets reducing unemployment to what percentage?", options: ["7%", "3%", "12%", "15%"], correct: 0, explanation: "Vision 2030 aims to reduce unemployment from 11.6% to 7% through job creation and Saudization.", hint: "A single-digit target that cuts the current rate roughly in half." },
  { id: 34, category: "vision", difficulty: 3, question: "Which stock exchange event was part of Vision 2030 economic reform?", options: ["Saudi Aramco IPO", "PIF privatization", "SABIC merger", "STC listing"], correct: 0, explanation: "The Saudi Aramco IPO in December 2019 raised $25.6 billion, the world's largest IPO, supporting Vision 2030.", hint: "The world's most valuable company went public in the world's largest IPO." },
  { id: 35, category: "vision", difficulty: 3, question: "What percentage of women in the workforce does Vision 2030 target?", options: ["30%", "10%", "50%", "20%"], correct: 0, explanation: "Vision 2030 aims to increase female workforce participation from 17% to 30% through reforms and opportunities.", hint: "Nearly doubling female participation to just under one-third." },

  // Difficulty 4
  { id: 36, category: "vision", difficulty: 4, question: "How many UNESCO World Heritage Sites does Vision 2030 aim to register?", options: ["Double the current number", "Triple", "Keep the same", "10 new sites"], correct: 0, explanation: "Vision 2030 aims to more than double Saudi Arabia's UNESCO sites as part of cultural heritage preservation.", hint: "The goal is multiplicative — more than twice what they have now." },
  { id: 37, category: "vision", difficulty: 4, question: "The National Transformation Program (NTP) targets how many government entities?", options: ["24", "10", "50", "5"], correct: 0, explanation: "The NTP 2020 targeted 24 government entities with 178 strategic objectives to support Vision 2030.", hint: "Two dozen government bodies were targeted for transformation." },
  { id: 38, category: "vision", difficulty: 4, question: "Vision 2030 aims for household spending on culture and entertainment to reach what percentage?", options: ["6%", "2%", "10%", "15%"], correct: 0, explanation: "Vision 2030 targets increasing household spending on cultural and entertainment activities from 2.9% to 6%.", hint: "Roughly doubling the current rate of about 3% — a single-digit goal." },
  { id: 39, category: "vision", difficulty: 4, question: "What global ranking for competitiveness does Vision 2030 target for Saudi Arabia?", options: ["Top 10", "Top 20", "Top 5", "Top 50"], correct: 0, explanation: "Vision 2030 aims to place Saudi Arabia among the top 10 most competitive countries globally.", hint: "An elite club — the top tier of global competitiveness." },
  { id: 40, category: "vision", difficulty: 4, question: "What is the target for small and medium enterprises' (SMEs) GDP contribution?", options: ["35%", "20%", "50%", "10%"], correct: 0, explanation: "Vision 2030 targets increasing SMEs' GDP contribution from 20% to 35% by supporting entrepreneurship.", hint: "The goal is about one-third of GDP — nearly doubling the current share." },

  // ═══════════════════════════════════
  //  SAUDI CULTURE & HERITAGE (20)
  // ═══════════════════════════════════

  // Difficulty 1
  { id: 41, category: "culture", difficulty: 1, question: "What is the traditional Saudi male garment called?", options: ["Thobe", "Kimono", "Sari", "Poncho"], correct: 0, explanation: "The thobe (or thawb) is a long white garment worn by Saudi men, ideal for the hot desert climate.", hint: "A long, flowing white garment perfect for desert heat." },
  { id: 42, category: "culture", difficulty: 1, question: "What is the national dish of Saudi Arabia?", options: ["Kabsa", "Sushi", "Pasta", "Tacos"], correct: 0, explanation: "Kabsa is Saudi Arabia's national dish — spiced rice with meat (usually chicken or lamb), served on a large platter.", hint: "A fragrant rice dish with meat — the pride of Saudi tables." },
  { id: 43, category: "culture", difficulty: 1, question: "What is Saudi Arabian coffee called?", options: ["Qahwa", "Espresso", "Chai", "Matcha"], correct: 0, explanation: "Qahwa (Arabic coffee) is a symbol of Saudi hospitality, flavored with cardamom and served in small cups called finjan.", hint: "The Arabic word for coffee — served with cardamom in tiny cups." },
  { id: 44, category: "culture", difficulty: 1, question: "What is the traditional Saudi sword dance called?", options: ["Ardah", "Salsa", "Tango", "Dabke"], correct: 0, explanation: "The Ardah is a traditional sword dance performed at cultural celebrations, representing Saudi heritage and bravery.", hint: "A traditional performance involving swords and rhythmic movement." },
  { id: 45, category: "culture", difficulty: 1, question: "What color is the Saudi Arabian flag?", options: ["Green with white Arabic text", "Red and white", "Blue and gold", "Black and green"], correct: 0, explanation: "The Saudi flag is green with the Shahada (Islamic declaration of faith) in white Arabic script and a sword.", hint: "The color of Islam — the same shade as the country's national identity." },

  // Difficulty 2
  { id: 46, category: "culture", difficulty: 2, question: "What is the headscarf worn by Saudi men called?", options: ["Shemagh or Ghutra", "Turban", "Fez", "Kippah"], correct: 0, explanation: "Saudi men wear a shemagh (red/white checkered) or ghutra (plain white) held in place by an igal (black cord).", hint: "It comes in two versions — checkered red/white or plain white." },
  { id: 47, category: "culture", difficulty: 2, question: "Janadriyah is a famous Saudi what?", options: ["Cultural and heritage festival", "Mountain range", "Shopping mall", "University"], correct: 0, explanation: "The Janadriyah Festival (now National Day celebrations) is Saudi Arabia's largest cultural heritage festival.", hint: "An annual celebration of Saudi traditions, crafts, and heritage." },
  { id: 48, category: "culture", difficulty: 2, question: "What is 'Mandi' in Saudi cuisine?", options: ["Slow-cooked meat and rice in an underground oven", "A type of bread", "A dessert", "A spiced drink"], correct: 0, explanation: "Mandi is a traditional dish where meat is slow-cooked in an underground tandoor oven, served over spiced rice.", hint: "Cooked underground for hours — meat so tender it falls off the bone." },
  { id: 49, category: "culture", difficulty: 2, question: "What are dates (Tamr) symbolically important for in Saudi culture?", options: ["Hospitality and generosity", "Medicine", "Currency", "Construction"], correct: 0, explanation: "Dates are a symbol of hospitality in Saudi Arabia, traditionally offered to guests alongside Arabic coffee.", hint: "They're the first thing offered to a guest alongside coffee." },
  { id: 50, category: "culture", difficulty: 2, question: "Saudi National Day is celebrated on which date?", options: ["September 23", "January 1", "December 25", "June 24"], correct: 0, explanation: "Saudi National Day on September 23 commemorates the unification of the Kingdom in 1932 by King Abdulaziz.", hint: "A date in autumn that marks the birth of the modern kingdom in 1932." },

  // Difficulty 3
  { id: 51, category: "culture", difficulty: 3, question: "What is 'Sadu' in Saudi heritage?", options: ["Traditional Bedouin weaving art", "A type of sword", "A greeting phrase", "A drum instrument"], correct: 0, explanation: "Sadu is the traditional Bedouin art of weaving colorful textiles, recognized by UNESCO as intangible cultural heritage.", hint: "A Bedouin craft that creates colorful patterns on fabric — recognized by UNESCO." },
  { id: 52, category: "culture", difficulty: 3, question: "The 'Mizmar' is a traditional Saudi what?", options: ["Musical instrument and folk dance", "Cooking utensil", "Farming tool", "Type of fabric"], correct: 0, explanation: "The Mizmar is both a wind instrument and a folk dance from the Hejaz region, performed at weddings and celebrations.", hint: "Both a wind instrument and a dance — popular at Hejazi weddings." },
  { id: 53, category: "culture", difficulty: 3, question: "What is 'Harees' in Saudi cuisine?", options: ["Wheat and meat porridge", "A fruit salad", "A type of bread", "Grilled vegetables"], correct: 0, explanation: "Harees is a traditional dish of cracked wheat slowly cooked with meat until smooth, popular during Ramadan.", hint: "A smooth, porridge-like dish especially popular during Ramadan." },
  { id: 54, category: "culture", difficulty: 3, question: "What does 'Bisht' refer to in Saudi dress?", options: ["A formal men's cloak worn over the thobe", "Women's headscarf", "Children's outfit", "Sports uniform"], correct: 0, explanation: "The Bisht is an elegant men's cloak in black or brown, worn over the thobe for formal occasions and celebrations.", hint: "An elegant outer layer for formal occasions — worn over the thobe." },
  { id: 55, category: "culture", difficulty: 3, question: "AlUla's Tantora Festival celebrates what?", options: ["Music, arts, and heritage under the stars", "Horse racing", "Oil industry", "Technology innovation"], correct: 0, explanation: "The Tantora Festival in AlUla features world-class concerts, art installations, and heritage experiences in a stunning ancient setting.", hint: "An outdoor cultural festival with concerts and art in an ancient canyon setting." },

  // Difficulty 4
  { id: 56, category: "culture", difficulty: 4, question: "The Saudi Falconry tradition is recognized by UNESCO as what?", options: ["Intangible Cultural Heritage of Humanity", "World Heritage Site", "Biosphere Reserve", "Natural Wonder"], correct: 0, explanation: "Falconry was inscribed on UNESCO's Intangible Cultural Heritage list, reflecting its deep roots in Saudi and Arab culture.", hint: "UNESCO recognizes this living tradition — it's about culture, not a physical place." },
  { id: 57, category: "culture", difficulty: 4, question: "What is 'Najdi' architecture characterized by?", options: ["Mud-brick buildings with triangular decorations", "Glass skyscrapers", "Wooden log cabins", "Stone pyramids"], correct: 0, explanation: "Najdi architecture features mud-brick buildings with distinctive triangular patterns, seen in historic Riyadh and Diriyah.", hint: "Traditional buildings made from desert materials with geometric patterns." },
  { id: 58, category: "culture", difficulty: 4, question: "What is the traditional incense 'Bukhoor' used for?", options: ["Perfuming homes and welcoming guests", "Cooking food", "Healing wounds", "Dyeing fabric"], correct: 0, explanation: "Bukhoor (incense made from woodchips soaked in fragrant oils) is burned to perfume homes, especially when welcoming guests.", hint: "Burned to fill the house with fragrance — part of Saudi hospitality." },
  { id: 59, category: "culture", difficulty: 4, question: "The Hejazi architectural style in Jeddah features what distinctive element?", options: ["Rawasheen (ornate wooden balconies)", "Glass domes", "Steel frames", "Underground rooms"], correct: 0, explanation: "Historic Jeddah (Al-Balad) features Rawasheen — intricately carved wooden balconies that provide shade and ventilation.", hint: "Ornate wooden structures on building facades in old Jeddah." },
  { id: 60, category: "culture", difficulty: 4, question: "What is the Saudi 'Samri' performance?", options: ["Bedouin poetry recital with percussion", "A sword-making craft", "A horse-riding competition", "A calligraphy art form"], correct: 0, explanation: "Samri is a traditional Bedouin performance art combining rhythmic poetry with percussion instruments, popular in Najd.", hint: "A Najdi art form that blends spoken word with drumming rhythms." },

  // ═══════════════════════════════════
  //  GEOGRAPHY & LANDMARKS (20)
  // ═══════════════════════════════════

  // Difficulty 1
  { id: 61, category: "geography", difficulty: 1, question: "What is the capital city of Saudi Arabia?", options: ["Riyadh", "Jeddah", "Mecca", "Medina"], correct: 0, explanation: "Riyadh is the capital and largest city of Saudi Arabia, located in the central Najd region.", hint: "The largest city in the country, located right in the center." },
  { id: 62, category: "geography", difficulty: 1, question: "Which sea borders Saudi Arabia to the west?", options: ["Red Sea", "Mediterranean Sea", "Caspian Sea", "Black Sea"], correct: 0, explanation: "The Red Sea forms Saudi Arabia's western border, stretching from the Gulf of Aqaba to the Strait of Bab el-Mandeb.", hint: "Its name is a color — and it separates Saudi Arabia from Africa." },
  { id: 63, category: "geography", difficulty: 1, question: "What is the largest desert in Saudi Arabia?", options: ["Rub' al Khali (Empty Quarter)", "Sahara", "Gobi", "Nafud"], correct: 0, explanation: "The Rub' al Khali (Empty Quarter) is the world's largest sand desert, covering much of southern Saudi Arabia.", hint: "Its English name suggests it's a vast, uninhabited space — a 'quarter' of emptiness." },
  { id: 64, category: "geography", difficulty: 1, question: "Which city is the holiest in Islam?", options: ["Mecca", "Riyadh", "Istanbul", "Cairo"], correct: 0, explanation: "Mecca (Makkah) is the holiest city in Islam, home to the Kaaba and the destination of the annual Hajj pilgrimage.", hint: "Home to the Kaaba — every Muslim faces this city during prayer." },
  { id: 65, category: "geography", difficulty: 1, question: "How many regions (provinces) does Saudi Arabia have?", options: ["13", "7", "20", "10"], correct: 0, explanation: "Saudi Arabia is divided into 13 administrative regions (provinces), each governed by an appointed emir.", hint: "A number between 10 and 15 — an unlucky number in some Western cultures." },

  // Difficulty 2
  { id: 66, category: "geography", difficulty: 2, question: "What is the 'Edge of the World' near Riyadh?", options: ["Dramatic cliff formations overlooking a vast valley", "A beach resort", "A volcano", "A river delta"], correct: 0, explanation: "The Edge of the World (Jebel Fihrayn) features dramatic 300m cliff faces with panoramic views of an ancient seabed.", hint: "Dramatic cliffs with a name that suggests you're at the planet's limit." },
  { id: 67, category: "geography", difficulty: 2, question: "Which Saudi city is known as the 'Bride of the Red Sea'?", options: ["Jeddah", "Yanbu", "Dammam", "Tabuk"], correct: 0, explanation: "Jeddah is nicknamed 'Bride of the Red Sea' due to its coastal beauty and status as a major port city.", hint: "Saudi Arabia's second-largest city and main port on the western coast." },
  { id: 68, category: "geography", difficulty: 2, question: "The Hejaz Mountains run along which part of Saudi Arabia?", options: ["Western coast", "Eastern coast", "Northern border", "Central plateau"], correct: 0, explanation: "The Hejaz Mountains (Sarawat range) run parallel to the western Red Sea coast, with peaks exceeding 2,500m.", hint: "They run parallel to the sea that borders Saudi Arabia to the west." },
  { id: 69, category: "geography", difficulty: 2, question: "What is the Gulf that borders Saudi Arabia to the east?", options: ["Arabian Gulf (Persian Gulf)", "Gulf of Mexico", "Gulf of Aden", "Gulf of Oman"], correct: 0, explanation: "The Arabian Gulf (also called the Persian Gulf) borders Saudi Arabia's Eastern Province, home to major oil fields.", hint: "This body of water shares its name with the Arabian Peninsula." },
  { id: 70, category: "geography", difficulty: 2, question: "Medina is the second holiest city in Islam because it contains what?", options: ["The Prophet Muhammad's Mosque and tomb", "The Kaaba", "Mount Sinai", "The Dead Sea Scrolls"], correct: 0, explanation: "Medina (Al-Madinah) is where the Prophet Muhammad migrated to and is buried, at Al-Masjid an-Nabawi.", hint: "The Prophet migrated here, and his final resting place is at its great mosque." },

  // Difficulty 3
  { id: 71, category: "geography", difficulty: 3, question: "What is Saudi Arabia's highest peak?", options: ["Jabal Sawda (~3,000m)", "Jabal Tuwayq (1,200m)", "Jabal Uhud (1,077m)", "Jabal Shammar (1,300m)"], correct: 0, explanation: "Jabal Sawda near Abha in the Asir region is Saudi Arabia's highest peak at approximately 3,000 meters.", hint: "Located near Abha in the green southwest — its name means 'Black Mountain'." },
  { id: 72, category: "geography", difficulty: 3, question: "The Farasan Islands in the Red Sea are known for what?", options: ["Marine biodiversity and coral reefs", "Oil rigs", "Desert sand dunes", "Volcanic activity"], correct: 0, explanation: "The Farasan Islands are a protected marine area with diverse coral reefs, mangroves, and sea life.", hint: "A protected archipelago teeming with underwater life and coral." },
  { id: 73, category: "geography", difficulty: 3, question: "Which Saudi region is famous for its Juniper forests?", options: ["Asir", "Najd", "Eastern Province", "Northern Borders"], correct: 0, explanation: "The Asir region in southwest Saudi Arabia is home to rare Juniper forests and has a cooler, greener climate.", hint: "The greenest, coolest region in Saudi Arabia — in the southwest." },
  { id: 74, category: "geography", difficulty: 3, question: "What is Hegra (Mada'in Saleh)?", options: ["An ancient Nabataean archaeological site", "A modern city", "A military base", "A nature reserve"], correct: 0, explanation: "Hegra (Mada'in Saleh) is Saudi Arabia's first UNESCO World Heritage Site, featuring Nabataean tombs from the 1st century.", hint: "Saudi's first UNESCO site — ancient tombs carved by the same people who built Petra." },
  { id: 75, category: "geography", difficulty: 3, question: "Al-Ahsa Oasis is famous for being what?", options: ["One of the world's largest natural oases", "A mountain range", "A volcanic field", "An island chain"], correct: 0, explanation: "Al-Ahsa Oasis is a UNESCO World Heritage Site and one of the world's largest oases with over 2.5 million palm trees.", hint: "Millions of palm trees in the desert — one of Earth's largest green refuges." },

  // Difficulty 4
  { id: 76, category: "geography", difficulty: 4, question: "The Harrat volcanic fields in Saudi Arabia contain how many craters?", options: ["Over 2,000", "About 50", "Around 500", "Less than 100"], correct: 0, explanation: "Saudi Arabia's Harrat lava fields contain over 2,000 volcanic craters, though most are dormant.", hint: "A surprisingly large number — think thousands, not hundreds." },
  { id: 77, category: "geography", difficulty: 4, question: "Wadi Hanifa runs through which Saudi city?", options: ["Riyadh", "Jeddah", "Mecca", "Tabuk"], correct: 0, explanation: "Wadi Hanifa is a 120km valley running through Riyadh, restored as a major green corridor and recreational area.", hint: "A green corridor running through the capital city." },
  { id: 78, category: "geography", difficulty: 4, question: "The Tuwaiq Escarpment is approximately how long?", options: ["800 km", "100 km", "2,000 km", "50 km"], correct: 0, explanation: "The Tuwaiq Escarpment stretches roughly 800 km through central Saudi Arabia, forming a dramatic arc of cliffs.", hint: "It stretches hundreds of kilometers through central Saudi Arabia." },
  { id: 79, category: "geography", difficulty: 4, question: "Dumat al-Jandal contains ruins of which ancient fortress?", options: ["Marid Castle", "Diriyah Palace", "Riyadh Fort", "Tabuk Castle"], correct: 0, explanation: "Dumat al-Jandal in Al-Jawf features the ancient Marid Castle and the Mosque of Omar, dating back centuries.", hint: "An ancient castle whose name suggests defiance and rebellion." },
  { id: 80, category: "geography", difficulty: 4, question: "What is the approximate total area of Saudi Arabia?", options: ["2.15 million km\u00B2", "1 million km\u00B2", "5 million km\u00B2", "500,000 km\u00B2"], correct: 0, explanation: "Saudi Arabia covers about 2.15 million km\u00B2, making it the largest country in the Middle East and 12th largest globally.", hint: "Over two million square kilometers — the biggest in the Middle East." },

  // ═══════════════════════════════════
  //  HISTORY & KINGS (20)
  // ═══════════════════════════════════

  // Difficulty 1
  { id: 81, category: "history", difficulty: 1, question: "Who founded the modern Kingdom of Saudi Arabia?", options: ["King Abdulaziz ibn Saud", "King Faisal", "King Fahd", "King Salman"], correct: 0, explanation: "King Abdulaziz ibn Abdulrahman Al Saud unified the kingdom and established modern Saudi Arabia on September 23, 1932.", hint: "The kingdom bears his family name — he unified it from many regions." },
  { id: 82, category: "history", difficulty: 1, question: "In which year was the Kingdom of Saudi Arabia officially founded?", options: ["1932", "1900", "1950", "1975"], correct: 0, explanation: "The Kingdom was officially proclaimed on September 23, 1932, unifying the regions of Hejaz, Najd, and others.", hint: "Early 1930s — between the two World Wars." },
  { id: 83, category: "history", difficulty: 1, question: "What is Diriyah historically significant for?", options: ["Birthplace of the first Saudi state", "Discovery of oil", "Building the first mosque", "First university"], correct: 0, explanation: "Diriyah was the capital of the First Saudi State (1727\u20131818) and the ancestral home of the Al Saud family.", hint: "The ancestral home of the ruling family and the very first Saudi capital." },
  { id: 84, category: "history", difficulty: 1, question: "When was oil first discovered in Saudi Arabia?", options: ["1938", "1920", "1950", "1900"], correct: 0, explanation: "Commercial quantities of oil were discovered in Dammam in March 1938, transforming Saudi Arabia's economy.", hint: "Late 1930s — just before World War II began." },
  { id: 85, category: "history", difficulty: 1, question: "Who is the current King of Saudi Arabia?", options: ["King Salman bin Abdulaziz", "King Fahd", "King Abdullah", "King Faisal"], correct: 0, explanation: "King Salman bin Abdulaziz Al Saud has been the King of Saudi Arabia since January 23, 2015.", hint: "He has been king since 2015 and his son is the famous Crown Prince." },

  // Difficulty 2
  { id: 86, category: "history", difficulty: 2, question: "How did King Abdulaziz recapture Riyadh in 1902?", options: ["A daring night raid on Masmak Fortress", "A naval battle", "A peace treaty", "A democratic election"], correct: 0, explanation: "In January 1902, young Abdulaziz led a bold nighttime raid to recapture Masmak Fortress, beginning his campaign to unify Arabia.", hint: "A bold, small-group attack under cover of darkness on a famous fortress." },
  { id: 87, category: "history", difficulty: 2, question: "King Faisal is remembered for what major international action?", options: ["The 1973 oil embargo", "Invading a neighboring country", "Abolishing the monarchy", "Joining NATO"], correct: 0, explanation: "King Faisal led the 1973 oil embargo against nations supporting Israel, dramatically increasing Saudi influence globally.", hint: "He used Saudi Arabia's most valuable resource as a geopolitical weapon in 1973." },
  { id: 88, category: "history", difficulty: 2, question: "The First Saudi State was established in which century?", options: ["18th century (1700s)", "15th century", "20th century", "12th century"], correct: 0, explanation: "The First Saudi State was established in 1727 when Muhammad ibn Saud allied with religious leader Muhammad ibn Abd al-Wahhab.", hint: "The 1700s — the same century as the American and French revolutions." },
  { id: 89, category: "history", difficulty: 2, question: "ARAMCO originally stood for what?", options: ["Arabian American Oil Company", "Arab Resources And Mining Corporation", "Arabian Advanced Mining Company", "Arab Republic of Minerals Corporation"], correct: 0, explanation: "ARAMCO (Arabian American Oil Company) was founded in 1933 and later became Saudi Aramco, the world's most valuable company.", hint: "A joint venture between Arabia and America — both are in the name." },
  { id: 90, category: "history", difficulty: 2, question: "The Masmak Fortress is located in which city?", options: ["Riyadh", "Jeddah", "Mecca", "Medina"], correct: 0, explanation: "The Masmak Fortress in central Riyadh is the site of King Abdulaziz's legendary 1902 raid that began Saudi unification.", hint: "In the heart of the capital — where the unification story began." },

  // Difficulty 3
  { id: 91, category: "history", difficulty: 3, question: "How many Saudi states have existed in history?", options: ["Three", "One", "Two", "Four"], correct: 0, explanation: "There have been three Saudi states: First (1727\u20131818), Second (1824\u20131891), and Third/current (1902\u2013present).", hint: "The current kingdom is actually the latest in a series — a small odd number." },
  { id: 92, category: "history", difficulty: 3, question: "Which King introduced television to Saudi Arabia?", options: ["King Faisal", "King Saud", "King Khalid", "King Abdulaziz"], correct: 0, explanation: "King Faisal introduced television broadcasting to Saudi Arabia in 1965, modernizing the country's media.", hint: "A modernizing king who also led the 1973 oil embargo." },
  { id: 93, category: "history", difficulty: 3, question: "The Treaty of Jeddah (1927) recognized Saudi sovereignty from which power?", options: ["Britain", "France", "Ottoman Empire", "United States"], correct: 0, explanation: "The Treaty of Jeddah in 1927 between King Abdulaziz and Britain recognized Saudi sovereignty over Hejaz and Najd.", hint: "The dominant colonial power in the Middle East during the 1920s." },
  { id: 94, category: "history", difficulty: 3, question: "King Khalid's reign is associated with what major infrastructure boom?", options: ["The oil wealth development era of the 1970s\u201380s", "Internet introduction", "Space program", "Nuclear energy"], correct: 0, explanation: "King Khalid's reign (1975\u20131982) saw massive infrastructure development funded by the oil boom of the late 1970s.", hint: "Oil prices skyrocketed and Saudi Arabia invested heavily in building the country." },
  { id: 95, category: "history", difficulty: 3, question: "What is the significance of the year 1744 in Saudi history?", options: ["Alliance between Muhammad ibn Saud and Muhammad ibn Abd al-Wahhab", "Oil discovery", "Kingdom founding", "First railway"], correct: 0, explanation: "In 1744, the pact between Muhammad ibn Saud and Sheikh Muhammad ibn Abd al-Wahhab formed the foundation of the First Saudi State.", hint: "A historic alliance between a ruler and a religious scholar that changed Arabia." },

  // Difficulty 4
  { id: 96, category: "history", difficulty: 4, question: "Which battle in 1929 consolidated King Abdulaziz's authority over the Ikhwan?", options: ["Battle of Sabilla", "Battle of Badr", "Battle of Mecca", "Battle of Tabuk"], correct: 0, explanation: "The Battle of Sabilla in 1929 saw King Abdulaziz defeat rebellious Ikhwan forces, cementing his control over the kingdom.", hint: "Named after the place where Abdulaziz crushed the Ikhwan rebellion." },
  { id: 97, category: "history", difficulty: 4, question: "Who destroyed the First Saudi State in 1818?", options: ["Egyptian-Ottoman forces under Ibrahim Pasha", "British forces", "Persian forces", "Rashidi forces"], correct: 0, explanation: "The Egyptian-Ottoman campaign led by Ibrahim Pasha destroyed the First Saudi State, razing Diriyah in 1818.", hint: "Forces from Egypt acting on behalf of the Ottoman Empire." },
  { id: 98, category: "history", difficulty: 4, question: "King Abdullah's KAUST university opened in which year?", options: ["2009", "2000", "2015", "1990"], correct: 0, explanation: "King Abdullah University of Science and Technology (KAUST) opened in 2009 as a world-class research university.", hint: "Late 2000s — the same year as the global financial crisis." },
  { id: 99, category: "history", difficulty: 4, question: "The Darin Pact of 1915 was between Saudi Arabia and which country?", options: ["Britain", "France", "Turkey", "Russia"], correct: 0, explanation: "The Treaty of Darin (1915) made Saudi territories a British protectorate in exchange for support against the Ottomans.", hint: "The same European power that signed the Treaty of Jeddah later in 1927." },
  { id: 100, category: "history", difficulty: 4, question: "What was the name of the Second Saudi State's capital?", options: ["Riyadh", "Diriyah", "Hofuf", "Ha'il"], correct: 0, explanation: "The Second Saudi State (1824\u20131891) was based in Riyadh after the destruction of Diriyah in the First Saudi State.", hint: "The same city that's the capital today — they moved there after Diriyah was destroyed." },

  // ═══════════════════════════════════
  //  ARABIC LANGUAGE (20)
  // ═══════════════════════════════════

  // Difficulty 1
  { id: 101, category: "arabic", difficulty: 1, question: "What does 'Marhaba' mean?", options: ["Hello / Welcome", "Goodbye", "Thank you", "Sorry"], correct: 0, explanation: "Marhaba (\u0645\u0631\u062D\u0628\u0627) is a common Arabic greeting meaning 'Hello' or 'Welcome'.", hint: "One of the first words you'd learn — used when meeting someone." },
  { id: 102, category: "arabic", difficulty: 1, question: "How do you say 'Thank you' in Arabic?", options: ["Shukran", "Marhaba", "Yalla", "Inshallah"], correct: 0, explanation: "Shukran (\u0634\u0643\u0631\u0627\u064B) means 'Thank you' and is one of the most common Arabic expressions worldwide.", hint: "Probably the most well-known Arabic word of gratitude." },
  { id: 103, category: "arabic", difficulty: 1, question: "What does 'Assalamu Alaikum' mean?", options: ["Peace be upon you", "Good morning", "How are you?", "See you later"], correct: 0, explanation: "Assalamu Alaikum (\u0627\u0644\u0633\u0644\u0627\u0645 \u0639\u0644\u064A\u0643\u0645) means 'Peace be upon you' and is the standard Islamic greeting.", hint: "The universal Islamic greeting — it's a wish for peace." },
  { id: 104, category: "arabic", difficulty: 1, question: "What does 'Yalla' mean in Saudi dialect?", options: ["Let's go / Come on", "Stop", "Wait", "Sleep"], correct: 0, explanation: "Yalla (\u064A\u0644\u0627) is one of the most popular Arabic expressions meaning 'Let's go!' or 'Come on!'", hint: "An energetic word that gets people moving — the opposite of 'wait'." },
  { id: 105, category: "arabic", difficulty: 1, question: "How many letters are in the Arabic alphabet?", options: ["28", "26", "30", "24"], correct: 0, explanation: "The Arabic alphabet has 28 letters, all of which are consonants. Vowels are indicated by diacritical marks.", hint: "Close to the English alphabet's count of 26, but slightly more." },

  // Difficulty 2
  { id: 106, category: "arabic", difficulty: 2, question: "What does 'Inshallah' mean?", options: ["God willing", "Thank God", "God is great", "God forgive me"], correct: 0, explanation: "Inshallah (\u0625\u0646 \u0634\u0627\u0621 \u0627\u0644\u0644\u0647) means 'God willing' and is used when speaking about future plans or hopes.", hint: "Used when talking about future plans — expressing hope that God wills it." },
  { id: 107, category: "arabic", difficulty: 2, question: "What does 'Mashallah' express?", options: ["Appreciation and praise (God has willed it)", "Sadness", "Anger", "Confusion"], correct: 0, explanation: "Mashallah (\u0645\u0627 \u0634\u0627\u0621 \u0627\u0644\u0644\u0647) expresses admiration and praise, literally meaning 'What God has willed'.", hint: "Said when admiring something beautiful or impressive." },
  { id: 108, category: "arabic", difficulty: 2, question: "In Saudi dialect, 'Keef halak?' means what?", options: ["How are you?", "What's your name?", "Where are you going?", "What time is it?"], correct: 0, explanation: "Keef halak (\u0643\u064A\u0641 \u062D\u0627\u0644\u0643\u061F) means 'How are you?' and is a common Saudi greeting.", hint: "A friendly question about someone's wellbeing — said right after hello." },
  { id: 109, category: "arabic", difficulty: 2, question: "What does 'Habibi' mean?", options: ["My dear / My love", "My friend", "My brother", "My teacher"], correct: 0, explanation: "Habibi (\u062D\u0628\u064A\u0628\u064A) means 'My dear' or 'My love' and is used affectionately for friends and loved ones.", hint: "The most famous Arabic term of endearment — used for loved ones." },
  { id: 110, category: "arabic", difficulty: 2, question: "Arabic is written in which direction?", options: ["Right to left", "Left to right", "Top to bottom", "Bottom to top"], correct: 0, explanation: "Arabic is written and read from right to left, which also affects page layouts and book binding.", hint: "The opposite direction from English — books open from the 'back'." },

  // Difficulty 3
  { id: 111, category: "arabic", difficulty: 3, question: "What is 'Fusha' Arabic?", options: ["Modern Standard Arabic (formal)", "A Saudi regional dialect", "Ancient Arabic", "A slang language"], correct: 0, explanation: "Fusha (\u0641\u0635\u062D\u0649) is Modern Standard Arabic, the formal language used in media, education, and official settings.", hint: "The formal version of Arabic used in news broadcasts and textbooks." },
  { id: 112, category: "arabic", difficulty: 3, question: "The Saudi expression 'Allah yisalmak' is a response to what?", options: ["Someone saying goodbye or thank you", "A sneeze", "Waking up", "Eating food"], correct: 0, explanation: "Allah yisalmak (\u0627\u0644\u0644\u0647 \u064A\u0633\u0644\u0645\u0643) means 'May God keep you safe' and is a polite response to thanks or farewells.", hint: "A prayer for someone's safety — said in reply to gratitude or farewell." },
  { id: 113, category: "arabic", difficulty: 3, question: "What does 'Wallah' mean in Saudi dialect?", options: ["I swear by God (emphasis)", "Wall", "Water", "Welcome"], correct: 0, explanation: "Wallah (\u0648\u0627\u0644\u0644\u0647) means 'I swear by God' and is commonly used for emphasis in Saudi conversation.", hint: "An emphatic expression invoking God — used to stress that you're serious." },
  { id: 114, category: "arabic", difficulty: 3, question: "What is the Arabic word for 'book'?", options: ["Kitab", "Qalam", "Bab", "Maktaba"], correct: 0, explanation: "Kitab (\u0643\u062A\u0627\u0628) means 'book'. Maktaba means 'library', Qalam means 'pen', and Bab means 'door'.", hint: "Shares the same root as 'Maktaba' (library) — the thing you read." },
  { id: 115, category: "arabic", difficulty: 3, question: "The phrase 'Bismillah' is said when?", options: ["Before starting any activity", "Before sleeping only", "After eating", "When angry"], correct: 0, explanation: "Bismillah (\u0628\u0633\u0645 \u0627\u0644\u0644\u0647) means 'In the name of God' and is said before starting any activity, especially eating.", hint: "Said at the beginning of actions — literally means 'In the name of God'." },

  // Difficulty 4
  { id: 116, category: "arabic", difficulty: 4, question: "What is unique about the Arabic letter 'Dhad' (\u0636)?", options: ["It's considered unique to Arabic (lughatu-d-dhad)", "It makes no sound", "It's the first letter", "It's never used"], correct: 0, explanation: "Arabic is sometimes called 'Lughatu-d-Dhad' (Language of Dhad) because this sound is considered unique to Arabic.", hint: "Arabic itself is sometimes named after this letter — it's that special." },
  { id: 117, category: "arabic", difficulty: 4, question: "What does 'Wasta' mean in Saudi/Arab culture?", options: ["Using connections/influence to get things done", "A type of food", "A prayer", "A holiday"], correct: 0, explanation: "Wasta (\u0648\u0627\u0633\u0637\u0629) refers to using personal connections or influence — a deeply embedded cultural concept in Arab societies.", hint: "A cultural practice of using who you know to open doors." },
  { id: 118, category: "arabic", difficulty: 4, question: "The Saudi expression 'Tislam' literally means what?", options: ["May you be safe", "You are strong", "You are right", "You are welcome"], correct: 0, explanation: "Tislam (\u062A\u0633\u0644\u0645) literally means 'May you be safe/well' and is used to express gratitude or appreciation.", hint: "Related to the word 'salam' (peace) — a wish for someone's safety." },
  { id: 119, category: "arabic", difficulty: 4, question: "How do you say 'one hundred' in Arabic?", options: ["Mi'a", "Alf", "Ashra", "Khamsin"], correct: 0, explanation: "Mi'a (\u0645\u0626\u0629) means 100. Alf means 1000, Ashra means 10, and Khamsin means 50.", hint: "Not 'Alf' (that's 1000) — this number is ten times 'Ashra' (10)." },
  { id: 120, category: "arabic", difficulty: 4, question: "What does 'Khalas' mean in Saudi dialect?", options: ["Enough / Done / Finished", "Beautiful", "Expensive", "Delicious"], correct: 0, explanation: "Khalas (\u062E\u0644\u0627\u0635) means 'Enough!', 'Done!', or 'Finished!' — one of the most versatile Saudi expressions.", hint: "You say this when something is finished or you want it to stop." },
];
